-- MySQL Script generated by MySQL Workbench
-- Tue Feb 10 10:37:30 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema SarahShelter
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema SarahShelter
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `SarahShelter` DEFAULT CHARACTER SET utf8 ;
USE `SarahShelter` ;

-- -----------------------------------------------------
-- Table `SarahShelter`.`Pets`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SarahShelter`.`Pets` (
  `PetId` INT NOT NULL AUTO_INCREMENT,
  `Animal` VARCHAR(45) NOT NULL,
  `Race` VARCHAR(45) NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `Owner` VARCHAR(45) NOT NULL,
  `Colours` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`PetId`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
