-- MySQL Script generated by MySQL Workbench
-- Tue Mar  3 10:17:31 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema crm_g2
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema crm_g2
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `crm_g2` DEFAULT CHARACTER SET utf8 ;
USE `crm_g2` ;

-- -----------------------------------------------------
-- Table `crm_g2`.`customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `crm_g2`.`customer` (
  `customer_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `address` VARCHAR(45) NULL,
  `phone_number` VARCHAR(14) NULL,
  `email` VARCHAR(70) NULL,
  PRIMARY KEY (`customer_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `crm_g2`.`contact_person`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `crm_g2`.`contact_person` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NULL,
  `last_name` VARCHAR(45) NULL,
  `phone_number` VARCHAR(14) NULL,
  `email` VARCHAR(70) NULL,
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `crm_g2`.`customer_has_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `crm_g2`.`customer_has_user` (
  `customer_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`customer_id`, `user_id`),
  INDEX `fk_customer_has_user_user1_idx` (`user_id` ASC),
  INDEX `fk_customer_has_user_customer_idx` (`customer_id` ASC),
  CONSTRAINT `fk_customer_has_user_customer`
    FOREIGN KEY (`customer_id`)
    REFERENCES `crm_g2`.`customer` (`customer_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_customer_has_user_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `crm_g2`.`contact_person` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `crm_g2`.`accounts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `crm_g2`.`accounts` (
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(255) NULL,
  `first_name` VARCHAR(45) NULL,
  `last_name` VARCHAR(45) NULL,
  `phone_number` VARCHAR(14) NULL,
  `email` VARCHAR(70) NULL,
  PRIMARY KEY (`username`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
