/**
 * @Author: William Berge Groensberg
 * @Date:   2026-03-13 13:07:37
 * @Last Modified by:   William Berge Groensberg
 * @Last Modified time: 2026-03-20 10:20:11
 */
-- MySQL Script generated by MySQL Workbench
-- Fri Mar  6 22:05:18 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema crm_g2
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema crm_g2
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `crm_g2` DEFAULT CHARACTER SET utf8 ;
USE `crm_g2` ;

-- -----------------------------------------------------
-- Table `crm_g2`.`customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `crm_g2`.`customer` (
  `customer_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `address` VARCHAR(45) NULL,
  `phone_number` VARCHAR(14) NULL,
  `kunde_siden` VARCHAR(45) NULL,
  PRIMARY KEY (`customer_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `crm_g2`.`contact_person`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `crm_g2`.`contact_person` (
  `person_id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NULL,
  `last_name` VARCHAR(45) NULL,
  `phone_number` VARCHAR(14) NULL,
  `email` VARCHAR(70) NULL,
  PRIMARY KEY (`person_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `crm_g2`.`customer_has_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `crm_g2`.`customer_has_user` (
  `customer_id` INT NOT NULL,
  `person_id` INT NOT NULL,
  PRIMARY KEY (`customer_id`, `person_id`),
  INDEX `fk_customer_has_user_user1_idx` (`person_id` ASC) ,
  INDEX `fk_customer_has_user_customer_idx` (`customer_id` ASC) ,
  CONSTRAINT `fk_customer_has_user_customer`
    FOREIGN KEY (`customer_id`)
    REFERENCES `crm_g2`.`customer` (`customer_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_customer_has_user_user1`
    FOREIGN KEY (`person_id`)
    REFERENCES `crm_g2`.`contact_person` (`person_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `crm_g2`.`accounts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `crm_g2`.`accounts` (
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(255) NULL,
  `first_name` VARCHAR(45) NULL,
  `last_name` VARCHAR(45) NULL,
  `phone_number` VARCHAR(14) NULL,
  `email` VARCHAR(70) NULL,
  `github_username` VARCHAR(45) NULL,
  PRIMARY KEY (`username`),
  UNIQUE INDEX `github_username_UNIQUE` (`github_username` ASC))
ENGINE = InnoDB;


-- lager table for å holde på tokens
CREATE TABLE password_reset_tokens (
    token VARCHAR(64) NOT NULL,
    username VARCHAR(45) NOT NULL,
    expires_at DATETIME NOT NULL,
    PRIMARY KEY (token),
    FOREIGN KEY (username) REFERENCES accounts(username) ON DELETE CASCADE
) ENGINE = InnoDB;

-- Legg til tre brukere
INSERT INTO `crm_g2`.`accounts` 
(`username`, `password`, `first_name`, `last_name`, `phone_number`, `email`, `github_username`) 
VALUES
('william', 'password123', 'William', 'Berge Grønsberg', '91131101', 'william@gmail.com', 'sneakyturtle270508'),
('iselin', 'password123', 'Iselin', 'Johnsen', '46841520', 'isetj1@gmail.com', 'IS3LIN'),
('sarah', 'password123', 'Sarah', 'Aadalen-Aasheim', '41334823', 'sti2711@skole.telemarkfylke.no', 'SRHTNIN'),
('sturle', 'password123', 'Sturle', 'Stiansen', '40606040', 'sturle@gmail.com', 'stusti');



SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
